export const seoKeywords = {
  swedish: [
    "gratis hemsida",
    "bygga hemsida gratis",
    "gratis webbdesign",
    "gratis webbsida",
    "gratis webbutveckling",
    "gratis hemsida för företag",
    "gratis hemsida för privatpersoner",
    "gratis hemsida för ideell förening",
    "gratis hemsida för organisation",
    "gratis hemsida för startup",
    "gratis hemsida för småföretag",
    "gratis hemsida för e-handel",
    "gratis hemsida för blogg",
    "gratis hemsida för portfolio",
    "gratis hemsida för restaurang",
    "gratis hemsida för frisör",
    "gratis hemsida för hantverkare",
    "gratis hemsida för konsult",
    "gratis hemsida för frilansare",
    "gratis hemsida utan kostnad",
    "gratis hemsida utan dolda avgifter",
    "gratis hemsida med domän",
    "gratis hemsida med hosting",
    "gratis hemsida med SSL",
    "gratis hemsida med SEO",
    "gratis hemsida med kontaktformulär",
    "gratis hemsida med bildgalleri",
    "gratis hemsida med blogg",
    "gratis hemsida med e-handel",
    "gratis hemsida med bokningssystem",
    "gratis hemsida med kalender",
    "gratis hemsida med medlemslogg",
    "gratis hemsida med betalningsintegration",
    "gratis hemsida med Stripe",
    "gratis hemsida med Swish",
  ],
  english: [
    "free website",
    "free website builder",
    "free website for small business",
    "free website for startup",
    "free website for non profit",
    "free web design",
    "free web development",
    "free website without cost",
    "free website no hidden fees",
    "free website with domain",
    "free website with hosting",
    "free website with SSL",
    "free website with SEO",
    "free website with contact form",
    "free website with gallery",
    "free website with blog",
    "free website with ecommerce",
    "free website with booking system",
    "free website with calendar",
    "free website with membership",
    "free website with Stripe",
    "free website with Swish",
  ],
  technology: [
    "Next.js utvecklare",
    "Next.js developer",
    "TypeScript utvecklare",
    "TypeScript developer",
    "React utvecklare",
    "React developer",
    "Tailwind CSS",
    "modern webbdesign",
    "modern web design",
    "responsiv webbdesign",
    "responsive web design",
    "SEO optimerad hemsida",
    "SEO optimized website",
    "snabba hemsidor",
    "fast websites",
    "prestanda optimerad",
    "performance optimized",
    "dark mode hemsida",
    "dark mode website",
    "realtidsuppdateringar",
    "real-time updates",
  ],
  longTail: [
    "hur får man en gratis hemsida",
    "var kan man bygga gratis hemsida",
    "bästa gratis hemsida för småföretag",
    "gratis hemsida utan månadskostnad",
    "gratis hemsida för alltid",
    "free website for life",
    "bygga hemsida själv gratis",
    "skapa hemsida gratis",
    "gratis hemsida utan reklam",
    "free website no ads",
    "gratis hemsida med egen domän",
    "free website with custom domain",
    "gratis hemsida för välgörenhet",
    "free website for charity",
    "gratis hemsida för ideell verksamhet",
  ],
  location: [
    "gratis hemsida Sverige",
    "free website Sweden",
    "gratis hemsida Stockholm",
    "gratis hemsida Göteborg",
    "gratis hemsida Malmö",
    "gratis hemsida Uppsala",
    "gratis hemsida Västerås",
    "gratis hemsida Örebro",
    "gratis hemsida Linköping",
    "gratis hemsida Helsingborg",
    "gratis hemsida Jönköping",
    "gratis hemsida Norrköping",
    "gratis hemsida Lund",
    "gratis hemsida Umeå",
    "gratis hemsida Gävle",
    "gratis hemsida Borås",
    "gratis hemsida Eskilstuna",
    "gratis hemsida Södertälje",
    "gratis hemsida Karlstad",
  ],
  userRoles: [
    "gratis hemsida för blivande föräldrar",
    "gratis hemsida för barnfamiljer",
    "gratis hemsida för pensionärer",
    "gratis hemsida för studenter",
    "gratis hemsida för arbetslösa",
    "gratis hemsida för nystartade företag",
    "free website for immigrants",
    "free website for refugees",
    "gratis hemsida för alla",
    "free website for everyone",
  ],
  problemSolving: [
    "behöver en hemsida men har ingen budget",
    "har inte råd med hemsida",
    "vill ha hemsida men är student",
    "startup behöver hemsida utan kostnad",
    "ideell förening behöver gratis hemsida",
    "församling behöver hemsida gratis",
  ],
  trust: [
    "pålitlig webbutvecklare",
    "trusted web developer",
    "erfaren webbutvecklare",
    "experienced web developer",
    "professionell hemsida gratis",
    "professional website free",
    "kvalitetshemsida gratis",
    "quality website free",
    "snygg hemsida gratis",
    "beautiful website free",
    "modern hemsida gratis",
    "modern website free",
  ],
};

// Kombinera alla sökord för användning i metadata
export const allKeywords = [
  ...seoKeywords.swedish,
  ...seoKeywords.english,
  ...seoKeywords.technology,
  ...seoKeywords.longTail,
  ...seoKeywords.location,
  ...seoKeywords.userRoles,
  ...seoKeywords.problemSolving,
  ...seoKeywords.trust,
];
